[package]
name = "sysmon-code"
author = "Tiara Hock <tiara.dev@proton.me>"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sysinfo = "0.32.0"
tokio = { version = "1.40.0", features = ["full"] }
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
